# Generated by Django 6.0.3 on 2026-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('overview', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('cast', models.TextField(blank=True, default='')),
                ('director', models.CharField(blank=True, default='', max_length=300)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(default=0.0)),
                ('poster_url', models.URLField(blank=True, default='', max_length=500)),
                ('release_date', models.CharField(blank=True, default='', max_length=20)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, default='')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
